const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.join(__dirname,'..');
const source=fs.readFileSync(path.join(root,'app.js'),'utf8').replace(/^import[\s\S]*?;\n/gm,'').replace(/bootstrap\(\)\.catch[\s\S]*$/,'');
const storage={getItem:()=>null};
const context=vm.createContext({console,Intl,Date,Set,URL,localStorage:storage,sessionStorage:storage,location:{hash:'#/dashboard'},document:{getElementById:()=>({}),documentElement:{dataset:{}}},PROJECT_TYPES:[{id:'custom',label:'Custom'}],COMMERCIAL_ROUTES:[{id:'fixed',label:'Fixed'}]});
vm.runInContext(source,context);
const run=code=>vm.runInContext(code,context);
run(`state.authReady=true;state.authUser={uid:'owner'};state.profile={roles:['owner'],status:'active',displayName:'Wisdom'};`);
assert.equal(run(`navFor('owner').map(x=>x[0]).join(',')`),'dashboard,projects,clients,finance');
for(const route of ['portfolio','reviews','packages'])assert.equal(run(`routeAllowed('${route}')`),false);
assert.match(run('publicLanding()'),/id="login-form"/);
assert.doesNotMatch(run('signupForm()'),/value="client"/);
assert.match(run('settingsView()'),/Team & permissions/);
assert.doesNotMatch(run('newProjectModal()'),/name="packageId"|name="workerIds"|name="serviceId"/);
run(`state.workspace.projects=[{id:'p',name:'Example',status:'active',accessUserIds:['owner'],managementUserIds:['owner'],workerIds:[],internalNotes:'<feedback>'}];`);
const detail=run(`projectDetail(state.workspace.projects[0])`);
assert.match(detail,/data-project-tab="notes"/);
assert.doesNotMatch(detail,/data-project-tab="reviews"|data-project-tab="delivery"/);
assert.match(run(`projectNotesTab(state.workspace.projects[0])`),/&lt;feedback&gt;/);
run(`state.profile={roles:['designer'],status:'active'};state.authUser={uid:'other'};`);
assert.match(run(`projectNotesTab(state.workspace.projects[0])`),/readonly/);
assert.doesNotMatch(run(`projectNotesTab(state.workspace.projects[0])`),/Save notes/);
run(`state.profile={roles:['owner','client'],status:'active'};state.workspaceRole='client';`);
assert.equal(run('actualRole()'),'owner');
run(`state.profile={roles:['client'],status:'active'};state.workspaceRole=null;`);
assert.match(run('renderRoute()'),/Client access is paused/);
run(`state.profile={roles:['owner'],status:'active'};state.authUser={uid:'owner'};state.workspace.invoices=[{id:'invoice',invoiceNo:'OVERDUE',status:'sent',amount:100,balance:50,dueDate:'2000-01-01',currency:'NGN'},{id:'draft',invoiceNo:'DRAFT',status:'draft',balance:100,dueDate:'2000-01-01'}];state.workspace.tasks=[{title:'DONE TASK',status:'approved',deadline:'2000-01-01'},{title:'DUE TASK',status:'in-progress',deadline:'2000-01-01'}];`);
const queue=run('actionQueue()');
assert.match(queue,/OVERDUE/);assert.match(queue,/DUE TASK/);
assert.doesNotMatch(queue,/DRAFT|DONE TASK/);
assert.match(run('ownerDashboard()'),/Outstanding/);
const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');
assert.doesNotMatch(css,/(linear|radial|conic)-gradient\(/);
console.log('Workspace smoke checks passed: routes, roles, forms, project tabs, notes access, receivables and deadline queue.');
